In [ ]:
#importing libraries
import pandas as pd
import numpy as np

In [ ]:
heart_dataset = pd.read_csv('/content/sample_data/heart failur classification dataset.csv')
heart_dataset.head(3)

Unnamed: 0   age  anaemia  ...  smoking  time  DEATH_EVENT
0           0  75.0        0  ...       No   4.0            1
1           1  55.0        0  ...       No   6.0            1
2           2  65.0        0  ...      Yes   7.0            1

[3 rows x 14 columns]

In [ ]:
heart_dataset.shape

(299, 14)

In [ ]:
heart_dataset.isnull().sum()

Unnamed: 0                  0
age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                6
sex                         0
smoking                     0
time                        7
DEATH_EVENT                 0
dtype: int64

dropping columns


In [ ]:
heart_dataset = heart_dataset.drop(['time'], axis = 1)
heart_dataset.shape
heart_dataset.isnull().sum()

Unnamed: 0                  0
age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                6
sex                         0
smoking                     0
DEATH_EVENT                 0
dtype: int64

dropping rows

In [ ]:
# Check how many values are missing in the serum_sodium column
print("Number of rows with null values in serum_sodium column: ", heart_dataset['serum_sodium'].isnull().sum())
# Subset the heart dataset
heart_dataset_subset = heart_dataset[heart_dataset['serum_sodium'].notnull()]
# Print out the shape of the subset
print("Shape after removing null values: ", heart_dataset_subset.shape)


Number of rows with null values in serum_sodium column:  6
Shape after removing null values:  (293, 13)


In [ ]:
print("Shape of dataframe before dropping:", heart_dataset.shape)
heart_dataset = heart_dataset.dropna(axis = 0, subset = ['serum_sodium'])
print("Shape after dropping:", heart_dataset.shape)

Shape of dataframe before dropping: (299, 13)
Shape after dropping: (293, 13)


Encoding Categorical Features

In [ ]:
heart_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 293 entries, 1 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                293 non-null    int64  
 1   age                       293 non-null    float64
 2   anaemia                   293 non-null    int64  
 3   creatinine_phosphokinase  293 non-null    int64  
 4   diabetes                  293 non-null    int64  
 5   ejection_fraction         293 non-null    int64  
 6   high_blood_pressure       293 non-null    int64  
 7   platelets                 293 non-null    float64
 8   serum_creatinine          293 non-null    float64
 9   serum_sodium              293 non-null    float64
 10  sex                       293 non-null    object 
 11  smoking                   293 non-null    object 
 12  DEATH_EVENT               293 non-null    int64  
dtypes: float64(4), int64(7), object(2)
memory usage: 32.0+ KB


In [ ]:
heart_dataset['sex'].unique()
heart_dataset['smoking'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Set up the LabelEncoder object
enc = LabelEncoder()
heart_dataset['sex']= enc.fit_transform(heart_dataset['sex'])
heart_dataset['smoking']= enc.fit_transform(heart_dataset['smoking'])
heart_dataset

Unnamed: 0   age  anaemia  ...  sex  smoking  DEATH_EVENT
1             1  55.0        0  ...    1        0            1
2             2  65.0        0  ...    1        1            1
3             3  50.0        1  ...    1        0            1
4             4  65.0        1  ...    0        0            1
5             5  90.0        1  ...    1        1            1
..          ...   ...      ...  ...  ...      ...          ...
293         293  63.0        1  ...    1        1            0
294         294  62.0        0  ...    1        1            0
296         296  45.0        0  ...    0        0            0
297         297  45.0        0  ...    1        1            0
298         298  50.0        0  ...    1        1            0

[293 rows x 13 columns]

Feature Scaling

In [ ]:
from sklearn.model_selection import train_test_split
y = pd.DataFrame(heart_dataset['DEATH_EVENT'])
X_train, X_test, y_train, y_test = train_test_split(heart_dataset, heart_dataset['DEATH_EVENT'], test_size = 0.25, random_state=0, stratify = y)

In [ ]:
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_train shape: (219, 13)
y_train shape: (219,)
X_test shape: (74, 13)
y_test shape: (74,)


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
#transform data
X_train_scaled = scaler.transform(X_train)  
X_train_scaled

array([[0.39393939, 0.45454545, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.18855219, 0.36363636, 1.        , ..., 1.        , 1.        ,
        0.        ],
       [0.003367  , 0.45454545, 0.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [0.64309764, 0.18181818, 1.        , ..., 1.        , 0.        ,
        0.        ],
       [0.01346801, 0.90909091, 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.49158249, 0.43636364, 0.        , ..., 1.        , 0.        ,
        0.        ]])

In [ ]:
print("per-feature minimum before scaling:\n {}".format(X_train.min(axis=0)))
print("per-feature maximum before scaling:\n {}".format(X_train.max(axis=0)))

per-feature minimum before scaling:
 Unnamed: 0                      1.0
age                            40.0
anaemia                         0.0
creatinine_phosphokinase       30.0
diabetes                        0.0
ejection_fraction              14.0
high_blood_pressure             0.0
platelets                   25100.0
serum_creatinine                0.5
serum_sodium                  113.0
sex                             0.0
smoking                         0.0
DEATH_EVENT                     0.0
dtype: float64
per-feature maximum before scaling:
 Unnamed: 0                     298.0
age                             95.0
anaemia                          1.0
creatinine_phosphokinase      7861.0
diabetes                         1.0
ejection_fraction               70.0
high_blood_pressure              1.0
platelets                   850000.0
serum_creatinine                 9.4
serum_sodium                   148.0
sex                              1.0
smoking                          1.0

In [ ]:
print("per-feature minimum after scaling:\n {}".format(
    X_train_scaled.min(axis=0)))
print("per-feature maximum after scaling:\n {}".format(
    X_train_scaled.max(axis=0)))

per-feature minimum after scaling:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
per-feature maximum after scaling:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# transform test data
X_test_scaled = scaler.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
scaler = MinMaxScaler()
scaler.fit(X_train)
#train
knn.fit(X_train_scaled, y_train)

# scoring on the scaled test set
print("Scaled test set accuracy: {:.2f}".format(knn.score(X_test_scaled, y_test)))

Scaled test set accuracy: 1.00
