In [287]:
import numpy as np
file = open('C:/Users/IMADN/Desktop/BFS/bfs2.txt', 'r')

In [288]:
#read vertex
line1 = file.readline().strip()
vertexcount=int(line1)

#read edge
line2 = file.readline().strip()
edgecount=int(line2)

#create adjmatrix
adjmatrix=np.zeros((vertexcount, vertexcount), dtype= 'int')
print(adjmatrix)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [289]:
for count in range(edgecount):
    line=file.readline().strip()
    
    if not line:
        break
    
    vertices=line.split(" ")
    u= int(vertices[0])
    v= int(vertices[1])
    print(u)
    print(v)
    
    adjmatrix[u][v]+=1
    adjmatrix[v][u]+=1

0
1
0
2
0
3
1
3
1
4
2
3
3
5
4
8
4
7
5
6
6
7
7
8


In [290]:
#lina
line3=file.readline().strip()
lina=int(line3)

#nora
line4=file.readline().strip()
nora=int(line4)

#lara
line5=file.readline().strip()
lara=int(line5)

print(lina)
print(nora)
print(lara)

7
5
3


In [291]:
#assigning value to matrix
for row in range(vertexcount):
    for col in range(vertexcount):
        print(adjmatrix[row][col], end=' ')
    print()

0 1 1 1 0 0 0 0 0 
1 0 0 1 1 0 0 0 0 
1 0 0 1 0 0 0 0 0 
1 1 1 0 0 1 0 0 0 
0 1 0 0 0 0 0 1 1 
0 0 0 1 0 0 1 0 0 
0 0 0 0 0 1 0 1 0 
0 0 0 0 1 0 1 0 1 
0 0 0 0 1 0 0 1 0 


In [292]:
color=np.empty((vertexcount), dtype="object")
color[:]="White"

In [293]:
parent=np.empty((vertexcount), dtype="object")
parent[:]=np.NaN

In [294]:
d=np.empty((vertexcount), dtype="int")
d[:]= 999999

In [295]:
#queue using queue model
from queue import Queue
#initializing queue
myqueue= Queue(maxsize= vertexcount)

In [301]:
#bfs function
def bfs(s):
    
    global color, parent, d
    
    color[:]='White'
    parent[:]=np.NaN
    d[:]=999999
    
    while not myqueue.empty():
        myqueue.get()   
    
    color[s] = 'Gray'
    parent[s]= np.nan
    d[s]= 0
    myqueue.put(s)
    while not myqueue.empty():
        u=myqueue.get() #popping element
        #print(u)
        for v in range(1, vertexcount):
            if adjmatrix[u][v]==1:
                if color[v] == 'White':
                    color[v]='Gray'
                    d[v]=d[u] +1
                    parent[v]=u
                    myqueue.put(v)
                    if v== lina:
                        return d[v]
                        break
                    
        color[u]= 'Black'

In [303]:
noraPosition=(bfs(nora))
laraPosition=(bfs(lara))

if noraPosition < laraPosition:
   print("Nora")
if laraPosition < noraPosition:
   print("Lara")
if noraPosition == laraPosition:
   print("Both")


Nora
